backwards :: (Num a) => [a] -> [a]
backwards [] = []
backwards (h : t) = backwards t ++ [h]

-- backwards [1,2,3] ++ [1]
-- backwards [2,3] ++ [2]
-- backwards [3] ++ [3]
-- backwards [] ++ []
-- [] ++ [3] ++ [2] ++ [1]
-- [3,2,1]

backwards' :: (Num a) => [a] -> [a]
backwards' [] = [99]
backwards' (h : t) = backwards' t ++ [h]

-- backwards [1,2,3] ++ [1]
-- backwards [2,3] ++ [2]
-- backwards [3] ++ [3]
-- backwards [] ++ [99]
-- [99] ++ [3] ++ [2] ++ [1]
-- [99,3,2,1]
